# -*- coding: utf-8 -*-
"""FineTuningDestilbert.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wWnS1l0IKr8V8xDXkr3kgNuCbtNM_e5p
"""

from google.colab import drive
drive.mount('/gdrive',force_remount=True)

"""# Setup"""

!pip install -qU transformers==4.48.3 datasets==3.2.0 optimum==1.24.0
!pip install -qU openai==1.61.0 wandb
!pip install langchain langchain-google-genai google-generativeai
!pip install sentence-transformers
!pip install -qU json-repair==0.29.1

!git clone --depth 1 https://github.com/hiyouga/LlamaFactory.git
!cd LlamaFactory && pip install -e .

from google.colab import userdata
import wandb

wandb.login(key=userdata.get('wandb'))
hf_token = userdata.get('HuggingFace')
!huggingface-cli login --token {hf_token}

"""##Imports"""

import os
from os.path import join
import random
from tqdm.auto import tqdm
import requests

from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
import torch
import pandas as pd
import json
import random
import os
from os.path import join
import json_repair

def parse_json(text):
    try:
        return json_repair.loads(text)
    except:
        return None


data_dir = "/gdrive/MyDrive/FineTuning_1"
base_model_id = "distilbert/distilbert-base-uncased"

device = "cuda"
torch_dtype = None

"""## Testing the model Without Finetuning"""

import pandas as pd

df = pd.read_excel("/gdrive/MyDrive/FineTuning_1/Datasets/data.xlsx")
df.head()

from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

embeddings = model.encode(df["query"].tolist())

query = "He said he would shoot me a message later."

query_embedding = model.encode([query])

from sklearn.metrics.pairwise import cosine_similarity

similarities = cosine_similarity(query_embedding, embeddings)


best_match_index = similarities.argmax()


answer = df.iloc[best_match_index]["query"]

print("Best match:", answer)
print("Category:", df.iloc[best_match_index]["Toxic Category"])

"""#Processing Data FOr FineTuning


"""

## Load Data

file_path = join(data_dir,"Datasets","data.xlsx")
df = pd.read_excel(file_path)
df.head()

df = df.dropna().reset_index(drop=True)

system_message ="\n".join([
  "You are a text classification model."
 "Predict the correct label based on the input."
])

llm_finetunning_data = []

for _, rec in df.iterrows():

    instruction = "\n".join([
        "# Query:",
        str(rec["query"]),

        "# Image Description:",
        str(rec["image descriptions"]),

        "# Task:",
        "Classify the input into the correct category.",

        "# Output:"
    ])

    llm_finetunning_data.append({
        "system": system_message,
        "instruction": instruction,
        "input": "",
        "output": str(rec["Toxic Category"]),
        "history": []
    })

random.Random(101).shuffle(llm_finetunning_data)

print(f"Raw data: {len(llm_finetunning_data)}")

train_sample_sz = int(len(llm_finetunning_data) * 0.8)

train_ds = llm_finetunning_data[:train_sample_sz]
eval_ds = llm_finetunning_data[train_sample_sz:]

out_dir = join(data_dir, "datasets", "llamafactory-finetune-data")
os.makedirs(out_dir, exist_ok=True)

with open(join(out_dir, "train.json"), "w", encoding="utf8") as f:
    json.dump(train_ds, f, ensure_ascii=False, indent=2)

with open(join(out_dir, "val.json"), "w", encoding="utf8") as f:
    json.dump(eval_ds, f, ensure_ascii=False, indent=2)


print("Train:", len(train_ds))
print("Val:", len(eval_ds))

join(data_dir, "datasets", "llamafactory-finetune-data", "val.json")

join(data_dir, "datasets", "llamafactory-finetune-data", "train.json")

"""## FineTuning"""

'''
"classify_text_finetuning_train": {
        "file_name": "/gdrive/MyDrive/FineTuning_1/datasets/llamafactory-finetune-data/train.json",
        "columns": {
            "prompt": "instruction",
            "query": "input",
            "response": "output",
            "system": "system",
            "history": "history"
        }
    },
    "classify_text_finetuning_val": {
        "file_name": "/gdrive/MyDrive/FineTuning_1/datasets/llamafactory-finetune-data/val.json",
        "columns": {
            "prompt": "instruction",
            "query": "input",
            "response": "output",
            "system": "system",
            "history": "history"
        }
    }
     '''

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/LlamaFactory/examples/train_lora/DistilBert_finetune.yaml
# 
# ## model
# model_name_or_path: distilbert/distilbert-base-uncased
# trust_remote_code: true
# 
# ## method
# stage: sft
# do_train: true
# finetuning_type: lora
# lora_rank: 64
# lora_target: all
# 
# ## Dataset
# dataset: classify_text_finetuning_train
# eval_dataset: classify_text_finetuning_val
# cutoff_len: 512
# overwrite_cache: true
# preprocessing_num_workers: 16
# 
# ## output
# output_dir: /gdrive/MyDrive/FineTuning_1/Text_classification
# logging_steps: 10
# save_steps: 500
# plot_loss: true
# 
# ### train
# per_device_train_batch_size: 1
# gradient_accumulation_steps: 8
# learning_rate: 2e-4
# num_train_epochs: 1.0
# lr_scheduler_type: cosine
# warmup_ratio: 0.1
# bf16: true
# ddp_timeout: 180000000
# 
# ### eval
# 
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 100
# 
# ## Wandb
# report_to: wandb
# run_name: Text_classification-finetune-llamafactory
# 
# ## HuggingFace
# push_to_hub: true
# export_hub_model_id: "ma7di/distilbert-finetunemodel"
# hub_private_repo: false
# hub_strategy: checkpoint
#

!cd LlamaFactory/ && llamafactory-cli train /content/LlamaFactory/examples/train_lora/DistilBert_finetune.yaml

